"""Constants and configuration for codebase analysis."""

LANGUAGE_EXTENSIONS = {
    ".py": "Python", ".js": "JavaScript", ".ts": "TypeScript", ".tsx": "TypeScript (React)",
    ".jsx": "JavaScript (React)", ".go": "Go", ".rs": "Rust", ".java": "Java",
    ".kt": "Kotlin", ".swift": "Swift", ".rb": "Ruby", ".php": "PHP",
    ".c": "C", ".cpp": "C++", ".h": "C/C++ Header", ".cs": "C#",
    ".scala": "Scala", ".clj": "Clojure", ".ex": "Elixir", ".erl": "Erlang",
    ".hs": "Haskell", ".lua": "Lua", ".r": "R", ".R": "R",
    ".dart": "Dart", ".vue": "Vue", ".svelte": "Svelte",
    ".sh": "Shell", ".bash": "Bash", ".zsh": "Zsh",
    ".sql": "SQL", ".graphql": "GraphQL", ".proto": "Protocol Buffers",
}

CONFIG_FILES = {
    "package.json": "Node.js project manifest",
    "package-lock.json": "npm lock file",
    "yarn.lock": "Yarn lock file",
    "pnpm-lock.yaml": "pnpm lock file",
    "tsconfig.json": "TypeScript configuration",
    "pyproject.toml": "Python project config (PEP 518)",
    "setup.py": "Python package setup (legacy)",
    "setup.cfg": "Python package config",
    "requirements.txt": "Python dependencies",
    "Pipfile": "Pipenv dependencies",
    "poetry.lock": "Poetry lock file",
    "Cargo.toml": "Rust project manifest",
    "Cargo.lock": "Rust lock file",
    "go.mod": "Go module definition",
    "go.sum": "Go dependency checksums",
    "Gemfile": "Ruby dependencies",
    "Gemfile.lock": "Ruby lock file",
    "build.gradle": "Gradle build (Java/Kotlin)",
    "build.gradle.kts": "Gradle Kotlin DSL build",
    "pom.xml": "Maven build (Java)",
    "Makefile": "Make build system",
    "CMakeLists.txt": "CMake build system",
    "docker-compose.yml": "Docker Compose services",
    "docker-compose.yaml": "Docker Compose services",
    "Dockerfile": "Docker container definition",
    ".dockerignore": "Docker ignore patterns",
    ".env.example": "Environment variable template",
    ".env.sample": "Environment variable template",
    "webpack.config.js": "Webpack bundler config",
    "vite.config.ts": "Vite bundler config",
    "vite.config.js": "Vite bundler config",
    "next.config.js": "Next.js config",
    "next.config.mjs": "Next.js config",
    "next.config.ts": "Next.js config",
    "nuxt.config.ts": "Nuxt.js config",
    ".eslintrc.json": "ESLint config",
    ".eslintrc.js": "ESLint config",
    ".prettierrc": "Prettier config",
    "jest.config.js": "Jest test config",
    "jest.config.ts": "Jest test config",
    "vitest.config.ts": "Vitest config",
    "pytest.ini": "Pytest config",
    "tox.ini": "Tox test config",
    ".github/workflows": "GitHub Actions CI/CD",
    ".gitlab-ci.yml": "GitLab CI/CD config",
    "Jenkinsfile": "Jenkins pipeline",
    ".circleci/config.yml": "CircleCI config",
    "terraform.tf": "Terraform infrastructure",
    "main.tf": "Terraform main config",
    "serverless.yml": "Serverless Framework config",
    "fly.toml": "Fly.io deployment config",
    "vercel.json": "Vercel deployment config",
    "netlify.toml": "Netlify deployment config",
    "railway.json": "Railway deployment config",
    "render.yaml": "Render deployment config",
    "Procfile": "Heroku/process manager config",
    ".pre-commit-config.yaml": "Pre-commit hooks",
    "renovate.json": "Renovate dependency updates",
    ".dependabot": "Dependabot config",
    "CODEOWNERS": "Code ownership rules",
    "CONTRIBUTING.md": "Contribution guidelines",
    "ARCHITECTURE.md": "Architecture documentation",
}

ENTRY_POINT_PATTERNS = [
    "main.py", "app.py", "server.py", "index.py", "cli.py", "manage.py", "__main__.py",
    "index.js", "index.ts", "app.js", "app.ts", "server.js", "server.ts",
    "main.js", "main.ts", "src/index.js", "src/index.ts", "src/main.ts",
    "src/App.tsx", "src/App.jsx", "src/app.tsx", "src/app.jsx",
    "main.go", "cmd/main.go", "main.rs", "src/main.rs", "src/lib.rs",
    "Program.cs", "Startup.cs",
]

IGNORE_DIRS = {
    "node_modules", ".git", "__pycache__", ".tox", ".pytest_cache",
    ".mypy_cache", "venv", ".venv", "env", ".env", "dist", "build",
    ".next", ".nuxt", "out", "target", ".cargo", "vendor",
    ".idea", ".vscode", ".DS_Store", "coverage", ".coverage",
    "htmlcov", "eggs", "*.egg-info", ".eggs", "bower_components",
}

MAX_FILE_READ_BYTES = 50_000  # 50KB per file
MAX_FILES_TO_ANALYZE = 2000

# Database indicators
DB_PACKAGES = {
    # Python
    "sqlalchemy": ("SQLAlchemy", "PostgreSQL/MySQL/SQLite"),
    "django.db": ("Django ORM", "PostgreSQL/MySQL/SQLite"),
    "tortoise": ("Tortoise ORM", "PostgreSQL/MySQL/SQLite"),
    "peewee": ("Peewee", "SQLite/PostgreSQL/MySQL"),
    "mongoengine": ("MongoEngine", "MongoDB"),
    "pymongo": ("PyMongo", "MongoDB"),
    "psycopg2": ("psycopg2", "PostgreSQL"),
    "asyncpg": ("asyncpg", "PostgreSQL"),
    "mysql-connector": ("MySQL Connector", "MySQL"),
    "redis": ("Redis", "Redis"),
    "celery": ("Celery", "Redis/RabbitMQ"),
    "elasticsearch": ("Elasticsearch", "Elasticsearch"),
    # JavaScript/TypeScript
    "prisma": ("Prisma", "PostgreSQL/MySQL/SQLite/MongoDB"),
    "sequelize": ("Sequelize", "PostgreSQL/MySQL/SQLite"),
    "typeorm": ("TypeORM", "PostgreSQL/MySQL/SQLite/MongoDB"),
    "mongoose": ("Mongoose", "MongoDB"),
    "knex": ("Knex.js", "PostgreSQL/MySQL/SQLite"),
    "drizzle-orm": ("Drizzle", "PostgreSQL/MySQL/SQLite"),
    "pg": ("node-postgres", "PostgreSQL"),
    "mysql2": ("mysql2", "MySQL"),
    "ioredis": ("ioredis", "Redis"),
    "better-sqlite3": ("better-sqlite3", "SQLite"),
    # Go
    "gorm.io": ("GORM", "PostgreSQL/MySQL/SQLite"),
    "database/sql": ("database/sql", "SQL Database"),
    "go.mongodb.org": ("MongoDB Go Driver", "MongoDB"),
    # Rust
    "diesel": ("Diesel", "PostgreSQL/MySQL/SQLite"),
    "sqlx": ("SQLx", "PostgreSQL/MySQL/SQLite"),
    "sea-orm": ("SeaORM", "PostgreSQL/MySQL/SQLite"),
}

# Auth indicators
AUTH_PACKAGES = {
    "passport": "Passport.js (Multi-strategy auth)",
    "jsonwebtoken": "JWT Authentication",
    "jose": "JWT/JWS/JWE (JOSE)",
    "bcrypt": "Password hashing (bcrypt)",
    "argon2": "Password hashing (Argon2)",
    "next-auth": "NextAuth.js",
    "auth0": "Auth0",
    "firebase-admin": "Firebase Auth",
    "supabase": "Supabase Auth",
    "clerk": "Clerk",
    "lucia": "Lucia Auth",
    "django.contrib.auth": "Django Auth",
    "flask-login": "Flask-Login",
    "flask-jwt-extended": "Flask JWT",
    "fastapi-users": "FastAPI Users",
    "python-jose": "Python JOSE (JWT)",
    "PyJWT": "PyJWT",
    "oauth2client": "OAuth2 Client",
    "authlib": "Authlib (OAuth/OIDC)",
    "social-auth": "Python Social Auth",
    "golang.org/x/oauth2": "Go OAuth2",
}
