"""Generate Markdown onboarding guide."""

import datetime
from ..models import RepoAnalysis
from collections import defaultdict


def generate_markdown(analysis: RepoAnalysis) -> str:
    """Generate a comprehensive Markdown onboarding guide."""
    a = analysis
    sections = []

    # Header
    sections.append(f"""# 🚀 Onboarding Guide: {a.name}

*Auto-generated by [Codebase Onboarding Agent](https://github.com/sagarjhaa/codebase-onboard) v1.0*
*Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}*

> This guide was generated by analyzing the repository structure, configuration files,
> source code, and dependencies. It provides a comprehensive starting point for understanding
> this codebase.""")

    # Complexity badge
    if a.complexity and a.complexity.overall > 0:
        emoji_map = {"Simple": "🟢", "Moderate": "🟡", "Complex": "🟠", "Very Complex": "🔴"}
        emoji = emoji_map.get(a.complexity.label, "⚪")
        sections[-1] += f"\n\n**Complexity: {emoji} {a.complexity.label}** ({a.complexity.overall}/100)"

    # Quick Overview
    sections.append(_quick_overview(a))

    # Tech Stack
    if a.languages:
        sections.append(_tech_stack(a))

    # Directory Structure
    if a.directory_structure:
        sections.append(f"""## 📂 Directory Structure

```
{a.directory_structure}
```""")

    # Architecture
    if a.architecture_hints or a.patterns:
        sections.append(_architecture(a))

    # API Endpoints
    if a.api_endpoints:
        sections.append(_api_endpoints(a))

    # Database
    if a.database_info and (a.database_info.databases or a.database_info.orms):
        sections.append(_database(a))

    # Auth
    if a.auth_info and (a.auth_info.patterns or a.auth_info.auth_files):
        sections.append(_auth(a))

    # Entry Points
    if a.entry_points:
        sections.append(_entry_points(a))

    # Key Files & Hot Files
    sections.append(_key_files(a))

    # Dependency Graph
    if a.dependency_graph:
        sections.append(f"""## 🔗 Dependency Graph

{a.dependency_graph}""")

    # Setup Guide
    sections.append(_setup_guide(a))

    # Patterns
    if a.patterns:
        sections.append(_patterns(a))

    # Dependencies
    if a.dependencies:
        sections.append(_dependencies(a))

    # Testing
    if a.test_coverage and a.test_coverage.test_count > 0:
        sections.append(_testing(a))

    # CI/CD
    if a.cicd_info and a.cicd_info.provider:
        sections.append(_cicd(a))

    # Docker
    if a.docker_info and (a.docker_info.has_dockerfile or a.docker_info.has_compose):
        sections.append(_docker(a))

    # Environment Variables
    if a.env_vars:
        sections.append(_env_vars(a))

    # Gotchas
    if a.gotchas:
        sections.append(_gotchas(a))

    # Key Concepts
    if a.key_concepts:
        sections.append(_key_concepts(a))

    # First PR Guide
    if a.first_pr and a.first_pr.suggested_areas:
        sections.append(_first_pr(a))

    # AI Insights
    if a.ai_insights:
        sections.append(f"""## 🤖 AI-Enhanced Insights

{a.ai_insights}""")

    # Next Steps
    sections.append(_next_steps(a))

    return "\n\n---\n\n".join(s for s in sections if s)


def _quick_overview(a: RepoAnalysis) -> str:
    lines = ["## 📋 Quick Overview", ""]

    if a.readme_content:
        paragraphs = a.readme_content.split("\n\n")
        desc_paras = [p for p in paragraphs if not p.strip().startswith("#")]
        if desc_paras:
            first = desc_paras[0].strip()[:500]
            lines.append(f"> {first}")
            lines.append("")

    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| **Primary Language** | {a.primary_language or 'N/A'} |")
    if a.frameworks:
        lines.append(f"| **Frameworks** | {', '.join(a.frameworks)} |")
    lines.append(f"| **Total Files** | {a.total_files:,} |")
    lines.append(f"| **Total Lines** | {a.total_lines:,} |")
    if a.license_type:
        lines.append(f"| **License** | {a.license_type} |")
    if a.package_manager:
        lines.append(f"| **Package Manager** | {a.package_manager} |")
    if a.test_coverage and a.test_coverage.test_frameworks:
        lines.append(f"| **Test Framework** | {', '.join(a.test_coverage.test_frameworks)} |")
    elif a.test_framework:
        lines.append(f"| **Test Framework** | {a.test_framework} |")
    if a.monorepo:
        lines.append("| **Monorepo** | Yes |")
    if a.database_info and a.database_info.databases:
        lines.append(f"| **Database** | {', '.join(a.database_info.databases)} |")
    if a.api_endpoints:
        lines.append(f"| **API Endpoints** | {len(a.api_endpoints)} detected |")
    if a.complexity:
        lines.append(f"| **Complexity** | {a.complexity.label} ({a.complexity.overall}/100) |")

    return "\n".join(lines)


def _tech_stack(a: RepoAnalysis) -> str:
    lines = ["## 🛠 Tech Stack", "", "### Languages"]
    total_lines = sum(a.languages.values())
    for lang, count in a.languages.items():
        pct = (count / total_lines * 100) if total_lines > 0 else 0
        bar = "█" * int(pct / 5) + "░" * (20 - int(pct / 5))
        lines.append(f"- **{lang}**: {count:,} lines ({pct:.1f}%) `{bar}`")

    if a.frameworks:
        lines.extend(["", "### Frameworks & Tools"])
        for fw in a.frameworks:
            lines.append(f"- {fw}")

    return "\n".join(lines)


def _architecture(a: RepoAnalysis) -> str:
    lines = ["## 🏗 Architecture Overview", ""]
    for hint in a.architecture_hints:
        lines.append(f"- {hint}")
    if a.patterns:
        lines.extend(["", "### Patterns & Conventions"])
        for p in a.patterns:
            lines.append(f"- {p}")
    return "\n".join(lines)


def _api_endpoints(a: RepoAnalysis) -> str:
    lines = ["## 🌐 API Endpoints", "",
             f"**{len(a.api_endpoints)} endpoint(s) detected:**", ""]

    # Group by file
    by_file = defaultdict(list)
    for ep in a.api_endpoints:
        by_file[ep.file].append(ep)

    for file, eps in by_file.items():
        lines.append(f"### `{file}`")
        lines.append("")
        lines.append("| Method | Path | Handler | Framework |")
        lines.append("|--------|------|---------|-----------|")
        for ep in eps[:30]:
            handler = ep.handler or "-"
            lines.append(f"| `{ep.method}` | `{ep.path}` | {handler} | {ep.framework} |")
        lines.append("")

    return "\n".join(lines)


def _database(a: RepoAnalysis) -> str:
    db = a.database_info
    lines = ["## 🗄️ Database", ""]

    if db.databases:
        lines.append(f"**Databases:** {', '.join(db.databases)}")
    if db.orms:
        lines.append(f"**ORM/Driver:** {', '.join(db.orms)}")
    if db.has_migrations:
        lines.append(f"**Migrations:** {db.migration_tool}")
    if db.models:
        lines.append(f"**Models:** {', '.join(db.models[:15])}")
    if db.connection_files:
        lines.append(f"**Connection config:** {', '.join(f'`{f}`' for f in db.connection_files[:5])}")

    return "\n".join(lines)


def _auth(a: RepoAnalysis) -> str:
    auth = a.auth_info
    lines = ["## 🔐 Authentication & Authorization", ""]

    if auth.patterns:
        lines.append("**Auth patterns:**")
        for p in auth.patterns:
            lines.append(f"- {p}")
    if auth.providers:
        lines.append(f"\n**OAuth providers:** {', '.join(auth.providers)}")
    if auth.has_rbac:
        lines.append("**RBAC:** Role-based access control detected")
    if auth.auth_files:
        lines.append(f"\n**Key auth files:** {', '.join(f'`{f}`' for f in auth.auth_files[:8])}")

    return "\n".join(lines)


def _entry_points(a: RepoAnalysis) -> str:
    lines = ["## 🚪 Entry Points", "",
             "Where execution begins:", ""]
    for ep in a.entry_points:
        lines.append(f"### `{ep.relative_path}`")
        if ep.functions:
            lines.append(f"- **Functions:** {', '.join(ep.functions[:10])}")
        if ep.classes:
            lines.append(f"- **Classes:** {', '.join(ep.classes[:10])}")
        key_imports = [i for i in ep.imports if not any(x in i for x in ("os", "sys", "re", "json", "typing"))][:5]
        if key_imports:
            lines.append(f"- **Key imports:** {', '.join(f'`{i[:80]}`' for i in key_imports)}")
        lines.append("")
    return "\n".join(lines)


def _key_files(a: RepoAnalysis) -> str:
    lines = ["## 📄 Key Files", ""]

    if a.config_files:
        lines.append("### Configuration")
        for cf in a.config_files[:20]:
            desc = cf.config_description or "Configuration file"
            lines.append(f"- **`{cf.relative_path}`** — {desc}")
        lines.append("")

    if a.hot_files:
        lines.append("### 🔥 Hot Files (most imported/changed)")
        for hf in a.hot_files[:10]:
            lines.append(f"- **`{hf.path}`** — {hf.reason}")
        lines.append("")

    source_files = sorted(
        [f for f in a.files if f.language and f.line_count > 0],
        key=lambda f: f.line_count, reverse=True
    )[:10]
    if source_files:
        lines.append("### Largest Source Files")
        for sf in source_files:
            details = []
            if sf.classes:
                details.append(f"classes: {', '.join(sf.classes[:3])}")
            if sf.functions:
                details.append(f"functions: {', '.join(sf.functions[:5])}")
            detail_str = f" — {'; '.join(details)}" if details else ""
            lines.append(f"- **`{sf.relative_path}`** ({sf.line_count} lines, {sf.language}){detail_str}")

    return "\n".join(lines)


def _setup_guide(a: RepoAnalysis) -> str:
    lines = ["## ⚡ Getting Started", ""]

    prereqs = []
    lang = a.primary_language
    if lang == "Python":
        prereqs.append("Python 3.8+")
    elif lang in ("JavaScript", "TypeScript", "TypeScript (React)", "JavaScript (React)"):
        prereqs.append("Node.js 18+ (LTS)")
    elif lang == "Go":
        prereqs.append("Go 1.21+")
    elif lang == "Rust":
        prereqs.append("Rust (latest stable via rustup)")
    if a.docker:
        prereqs.append("Docker & Docker Compose")

    if prereqs:
        lines.extend(["### Prerequisites"] + [f"- {p}" for p in prereqs] + [""])

    lines.extend(["### Installation", "", "```bash"])
    if a.url:
        lines.extend([f"git clone {a.url}", f"cd {a.name}", ""])

    pm_install = {
        "npm": "npm install", "yarn": "yarn install", "pnpm": "pnpm install",
        "bun": "bun install",
        "pip": "python3 -m venv venv\nsource venv/bin/activate\npip install -r requirements.txt",
        "poetry": "poetry install", "pipenv": "pipenv install --dev",
        "go modules": "go mod download", "cargo": "cargo build",
        "bundler": "bundle install",
    }
    if a.package_manager in pm_install:
        lines.append(pm_install[a.package_manager])

    if a.env_vars:
        lines.append("")
        has_example = any(isinstance(v, str) and v.endswith((".env.example", ".env.sample"))
                         for ev in a.env_vars for v in (ev if isinstance(ev, tuple) else [ev]))
        # Check files directly
        has_example_file = any(f.relative_path.endswith((".env.example", ".env.sample")) for f in a.files)
        if has_example_file:
            lines.extend(["cp .env.example .env", "# Edit .env with your values"])
        else:
            lines.append("# Create .env with required variables (see Environment Variables section)")

    lines.append("```")

    if a.scripts:
        lines.extend(["", "### Available Scripts", ""])
        runner = a.package_manager if a.package_manager in ("npm", "yarn", "pnpm", "bun") else ""
        for name, cmd in list(a.scripts.items())[:15]:
            prefix = f"{runner} run " if runner else ""
            lines.append(f"- **`{prefix}{name}`** — `{cmd}`")

    return "\n".join(lines)


def _patterns(a: RepoAnalysis) -> str:
    lines = ["## 🔄 Patterns & Conventions", ""]
    for p in a.patterns:
        lines.append(f"- {p}")
    return "\n".join(lines)


def _dependencies(a: RepoAnalysis) -> str:
    lines = ["## 📦 Dependencies", ""]

    deps = a.dependencies
    if len(deps) > 30:
        lines.extend([f"**{len(deps)} dependencies.** Key ones:", ""])

    categories = defaultdict(list)
    for name, version in deps.items():
        name_lower = name.lower()
        if any(x in name_lower for x in ("express", "fastify", "koa", "flask", "django", "fastapi", "gin", "axum", "actix", "hono")):
            categories["Web Framework"].append((name, version))
        elif any(x in name_lower for x in ("react", "vue", "svelte", "angular", "next", "nuxt")):
            categories["Frontend"].append((name, version))
        elif any(x in name_lower for x in ("prisma", "sequelize", "typeorm", "mongoose", "sqlalchemy", "knex", "drizzle")):
            categories["Database/ORM"].append((name, version))
        elif any(x in name_lower for x in ("jest", "mocha", "pytest", "vitest", "cypress", "playwright")):
            categories["Testing"].append((name, version))
        elif any(x in name_lower for x in ("eslint", "prettier", "typescript", "babel", "webpack", "vite")):
            categories["Build/Lint"].append((name, version))
        elif any(x in name_lower for x in ("aws", "azure", "gcp", "firebase", "supabase", "redis", "kafka")):
            categories["Cloud/Infrastructure"].append((name, version))
        elif any(x in name_lower for x in ("auth", "jwt", "passport", "oauth", "bcrypt")):
            categories["Auth/Security"].append((name, version))
        else:
            categories["Other"].append((name, version))

    for cat, items in categories.items():
        if not items:
            continue
        if cat == "Other" and len(items) > 15:
            lines.append(f"### {cat} ({len(items)} packages)")
            for name, ver in items[:10]:
                lines.append(f"- `{name}` {ver}")
            lines.append(f"- *... and {len(items) - 10} more*")
        else:
            lines.append(f"### {cat}")
            for name, ver in items:
                lines.append(f"- `{name}` {ver}")
        lines.append("")

    return "\n".join(lines)


def _testing(a: RepoAnalysis) -> str:
    tc = a.test_coverage
    lines = ["## 🧪 Testing", ""]

    if tc.test_frameworks:
        lines.append(f"**Frameworks:** {', '.join(tc.test_frameworks)}")
    lines.append(f"**Test files:** {tc.test_count}")
    lines.append(f"**Coverage estimate:** {tc.coverage_estimate.title()}")
    lines.append(f"**Test-to-source ratio:** {tc.source_to_test_ratio:.2f}")

    if tc.test_dirs:
        lines.extend(["", "**Test locations:**"])
        for dir_name, count in tc.test_dirs:
            lines.append(f"- `{dir_name}/`: {count} test files")

    lines.extend(["", "### Running Tests", "", "```bash"])
    if "pytest" in str(tc.test_frameworks):
        lines.extend(["pytest", "pytest --cov  # with coverage"])
    elif "Jest" in str(tc.test_frameworks):
        lines.extend(["npm test", "npx jest --watch  # watch mode"])
    elif "Vitest" in str(tc.test_frameworks):
        lines.extend(["npx vitest", "npx vitest --watch"])
    elif a.test_framework:
        runner = a.package_manager if a.package_manager in ("npm", "yarn", "pnpm") else "npm"
        lines.append(f"{runner} test")
    else:
        lines.append("# Check project docs for test commands")
    lines.append("```")

    return "\n".join(lines)


def _cicd(a: RepoAnalysis) -> str:
    ci = a.cicd_info
    lines = ["## 🔄 CI/CD", ""]

    lines.append(f"**Provider:** {ci.provider}")
    if ci.config_files:
        lines.append(f"**Config files:** {', '.join(f'`{f}`' for f in ci.config_files)}")

    features = []
    if ci.has_test:
        features.append("✅ Tests")
    if ci.has_lint:
        features.append("✅ Linting")
    if ci.has_build:
        features.append("✅ Build")
    if ci.has_deploy:
        features.append("✅ Deploy")
    if features:
        lines.append(f"**Pipeline features:** {' | '.join(features)}")

    if ci.pipelines:
        lines.extend(["", "### Pipelines"])
        for p in ci.pipelines:
            lines.append(f"- {p}")

    if ci.environments:
        lines.append(f"\n**Environments:** {', '.join(ci.environments)}")

    return "\n".join(lines)


def _docker(a: RepoAnalysis) -> str:
    d = a.docker_info
    lines = ["## 🐳 Docker", ""]

    if d.base_images:
        lines.append(f"**Base images:** {', '.join(f'`{img}`' for img in d.base_images)}")
    if d.exposed_ports:
        lines.append(f"**Exposed ports:** {', '.join(d.exposed_ports)}")

    if d.services:
        lines.extend(["", "### Docker Compose Services"])
        for svc in d.services:
            details = d.compose_services.get(svc, {})
            image = details.get("image", "")
            ports = details.get("ports", [])
            detail_parts = []
            if image:
                detail_parts.append(f"image: `{image}`")
            if ports:
                detail_parts.append(f"ports: {', '.join(ports)}")
            detail_str = f" — {', '.join(detail_parts)}" if detail_parts else ""
            lines.append(f"- **{svc}**{detail_str}")

    lines.extend(["", "### Quick Start", "", "```bash"])
    if d.has_compose:
        lines.extend(["docker-compose up -d", "docker-compose logs -f"])
    elif d.has_dockerfile:
        lines.extend([f"docker build -t {a.name} .", f"docker run -p 8080:8080 {a.name}"])
    lines.append("```")

    return "\n".join(lines)


def _env_vars(a: RepoAnalysis) -> str:
    lines = ["## 🔐 Environment Variables", ""]

    if isinstance(a.env_vars, list) and a.env_vars and isinstance(a.env_vars[0], tuple):
        lines.append("| Variable | Referenced In |")
        lines.append("|----------|-------------|")
        for name, file_list in a.env_vars[:30]:
            files_str = ", ".join(f"`{f}`" for f in file_list[:3])
            if len(file_list) > 3:
                files_str += f" +{len(file_list) - 3} more"
            lines.append(f"| `{name}` | {files_str} |")
        if len(a.env_vars) > 30:
            lines.append(f"\n*... and {len(a.env_vars) - 30} more variables*")
    else:
        for var in (a.env_vars if isinstance(a.env_vars, list) else []):
            lines.append(f"- `{var}`")

    lines.append("\n*Check `.env.example` or ask your team for values.*")
    return "\n".join(lines)


def _gotchas(a: RepoAnalysis) -> str:
    lines = ["## ⚠️ Gotchas & Potential Issues", ""]
    for g in a.gotchas:
        lines.append(f"- {g}")

    all_todos = [(f.relative_path, todo) for f in a.files for todo in f.todos]
    if all_todos:
        lines.extend(["", "### Notable TODOs/FIXMEs", ""])
        for path, todo in all_todos[:15]:
            lines.append(f"- `{path}`: {todo[:120]}")
        if len(all_todos) > 15:
            lines.append(f"- *... and {len(all_todos) - 15} more*")

    return "\n".join(lines)


def _key_concepts(a: RepoAnalysis) -> str:
    lines = ["## 💡 Key Concepts & Terminology", ""]
    lines.append("Domain-specific terms and abstractions found in the codebase:")
    lines.append("")
    for concept in a.key_concepts[:15]:
        lines.append(f"- **`{concept['term']}`** — found in `{concept['file']}`")
    return "\n".join(lines)


def _first_pr(a: RepoAnalysis) -> str:
    fp = a.first_pr
    lines = ["## 🎯 Your First PR", ""]

    lines.append("### Suggested Areas")
    for area in fp.suggested_areas:
        lines.append(f"- {area}")

    if fp.conventions:
        lines.extend(["", "### Conventions to Follow"])
        for conv in fp.conventions:
            lines.append(f"- {conv}")

    if fp.good_first_files:
        lines.extend(["", "### Good First Files to Explore"])
        for f in fp.good_first_files[:8]:
            lines.append(f"- `{f}`")

    return "\n".join(lines)


def _next_steps(a: RepoAnalysis) -> str:
    lines = [
        "## 🗺️ Next Steps",
        "",
        "1. **Read the README** thoroughly",
        "2. **Set up your dev environment** using the steps above",
        "3. **Run the tests** to verify everything works",
    ]

    step = 4
    if a.entry_points:
        ep_list = ", ".join(f"`{ep.relative_path}`" for ep in a.entry_points[:3])
        lines.append(f"{step}. **Explore the entry points**: {ep_list}")
        step += 1

    if a.api_endpoints:
        lines.append(f"{step}. **Review API endpoints** — understand the public interface")
        step += 1

    if a.cicd_info and a.cicd_info.provider:
        lines.append(f"{step}. **Check CI/CD pipelines** — understand the deployment process")
        step += 1

    lines.extend([
        "",
        "### Questions to Ask Your Team",
        "",
        "- What's the branching strategy?",
        "- What's the PR review process?",
        "- Are there ongoing refactors to be aware of?",
        "- Who owns which parts? (Check CODEOWNERS if it exists)",
        "- What's the deployment process and cadence?",
        "- Any external services/systems not in this repo?",
    ])

    return "\n".join(lines)
